# Generated by Django 4.1.5 on 2023-01-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assest', '0002_rename_snippet_assest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assest',
            options={},
        ),
    ]
